### PR TITLE
Disable bash chunks on windows as per https://github.com/jennybc/happ…

### PR DESCRIPTION
**Pull request by aDeLe24**
Disable bash chunks on windows as per https://github.com/jennybc/happy-git-with-r/issues/120

### CODE REVIEW

**Comment by jennybc** [comment]
Yes I want to do this. I have a few questions to throw to some external folks:

@jimhester Is `Sys.info()['sysname']!= "Windows"` our best "house style" for detecting Windows?

@yihui Is there any clever pattern that would allow us to add a comment to chunks that are conditionally not evaluated on Windows? Ideally, we would insert a comment saying "unable to render this chunk, falling back to inclusion of unevaluate code" or similar.

I write the prose of the book assuming the chunk will include output, so it would be nice to tip someone off to this possible reason for the prose and the chunk seeming to not match.

**Comment by yihui** [comment]
With the "Windows Subsystem for Linux", it might actually be possible to run bash chunks on Windows. I'm not totally sure. I'd use

```r
eval=Sys.which('bash') != ''
```

but who knows what *nix commands can run on Windows: https://github.com/yihui/hugo-xmin/issues/19... so I may disable it on Windows, too:

```r
eval=Sys.which('bash') != '' && .Platform$OS.type != 'windows'
```

If this is too much to type, you can use an option hook to set `eval` to `FALSE` automatically:

```r
knitr::opts_hook$set(eval = function(options) {
  if (options$engine == 'bash' && options$eval) {
    options$eval = Sys.which('bash') != '' && .Platform$OS.type != 'windows'
  }
  options
})
```

**Comment by jimhester** [comment]
Maybe we could just define the following in a setup chunk

```r
has_bash <- Sys.which('bash') != '' && .Platform$OS.type != 'windows'
```
then you could use `eval = has_bash` in the individual chunks.

I don't think there would be a way to put replacement text if bash is not available without defining a custom output hook for the chunk...

**Comment by jennybc** [comment]
Thanks @aDeLe24 for initiating this!

In the future, I may yet decide to remove these few executable bash chunks and just include indicative output, as I do elsewhere. I'm not sure I gain enough to make these chunks executable.

Please let me know if this does NOT fix your ability to render the book, though!

**Pull request merged**
