### PR TITLE
add link to OpenSearch plugin; improve paragraph separation

### PR DESCRIPTION
**Pull request by salim-b**
I found this custom GitHub search to be such a powerful thing that I had to build a custom OpenSearch plugin for convenience. I've added the link to it in the hope that others find it useful as well.

### CODE REVIEW

**Comment by jennybc** [comment]
I'm pretty conservative about linking to something that's new-ish and that I don't control or use, although am *totally glad* you've made this. If I go to that URL right now, the top image (?) is very large and just displays a question mark. I guess it illustrates why I've grown so conservative about such things.

**Comment by salim-b** [comment]
> I'm pretty conservative about linking to something that's new-ish

Well, the OpenSearch standard certainly isn't "new-ish"... it has been around for over a decade. See [the Wikipedia article](https://en.wikipedia.org/wiki/OpenSearch) or [MDN](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) for some technical documentation.

> If I go to that URL right now, the top image (?) is very large and just displays a question mark.

That's weird. It's the first site I've built using Hugo so I'm not particularly experienced. But the site works on all my devices as expected and should look like this (desktop):

screenshot-2018-1-23 github r cran opensearch plugins by salim b

Did you go to that exact URL? https://salim_b_public.gitlab.io/opensearch_plugins/github-r/
If so, could you provide a screenshot?

**Comment by jennybc** [comment]
If I go to this url:

https://salim_b_public.gitlab.io/opensearch_plugins/github-r/

I see this (had to take multiple screenshots)

screen shot 2018-01-23 at 3 22 10 pm

screen shot 2018-01-23 at 3 22 51 pm

screen shot 2018-01-23 at 3 23 24 pm

**Comment by salim-b** [comment]
> I see this (had to take multiple screenshots)

Thanks! That's indeed not the intended look... 😅  The embedded Tweet looks the same in Chrome on my machine but the huge image placeholder shouldn't be there of course.

What browser and OS do you use?

**Comment by jennybc** [comment]
Screenshot is from Mac OS Sierra, Safari 11.0.2. I'm in the midst of a migration to a new system, but there you go.

**Comment by salim-b** [comment]
Most browsers seem to hide this non-existent image automatically but Safari obviously takes a different road there... anyway, after a lot of fiddling around I managed to track down the exact origin of the image (turned out to be an issue with the Hugo theme). It should be fixed now.

BTW: To make any senseful use of the OpenSearch plugin in Safari you might need to use [this extension](http://www.opensearchforsafari.com/). I don't own a Mac, so I can't really tell but after some googling I think Safari doesn't support the manual addition of search plugins (only some auto-discovery which might not work on subpages like this one; at least that's the case in Chrome). I'd be glad if you could tell me what happens when you click on the button `Add this search plugin to my browser`.

**Comment by salim-b** [comment]
I've changed the URL. The currently linked site is here to stay, I promise 🤞

**Comment by salim-b** [comment]
> BTW: To make any senseful use of the OpenSearch plugin in Safari you might need to use this extension. I don't own a Mac, so I can't really tell but after some googling I think Safari doesn't support the manual addition of search plugins (only some auto-discovery which might not work on subpages like this one; at least that's the case in Chrome). I'd be glad if you could tell me what happens when you click on the button Add this search plugin to my browser.

In the meantime I had the opportunity to test it on Safari. It doesn't support the OpenSearch standard out-of-the-box. Unfortunately using the mentioned extension doesn't really help either. Although after installing it you're able to add OpenSearch plugins it doesn't fully support the standard: The URL parameters of the custom search (i.a. `language:R`, `user:cran`) seem to get ignored and only a generic search on the whole GitHub site is performed – so it's mostly useless... 😒 

Anyway, on Firefox it works like a charm (also on IE versions before Edge; don't know about Opera). Therefore I've added a hint about FF on the website.

**Comment by jennybc** [comment]
I'm in the midst of refreshing Happy Git and reminded of the challenges of linking to outside resources. Thanks again for this but I'm going to close.

**Pull request closed without merging**
