### PR TITLE
Update GitHub Desktop Git client description

### LINKED ISSUE #136: Revise treatment of GitHub Desktop client
Looks like it may be time to revisit our negativity re: GitHub's Desktop client.

From a [twitter conversation](
https://twitter.com/billygriffin22/status/1104097810679361536) with @billygriffin:

> Thank you! The two issues you mentioned are both no longer things in the latest version. The button formerly known as "Sync" now displays Fetch/Pull/Push depending on the state, and we ask that users use Git for Windows as it's become a more supported project.

### PR DESCRIPTION
**Pull request by billygriffin**
Closes #136 

This updates the description of GitHub Desktop to remove the portion that referred to the old version of the app, along with a value proposition for people likely using this guide. 😄

### CODE REVIEW

**Comment by billygriffin** [comment]
@jennybc Here's a first stab! I'm not 100% sure why this is showing the diff with the work from my previous PR as well, as I thought that had already been merged, but happy to close this one and start another fresh fork if something's not going to be quite right when merging this. Just let me know, and thanks for your openness to revisiting!

**Comment by jennybc** [comment]
Thanks. I might create my own change, but this PR is very helpful.

Excuse me if we've covered this in a previous conversation ... but does the Desktop client still install command line git and, if so, where?

**Comment by billygriffin** [comment]
No worries at all! 

Desktop doesn’t directly install Git, but on Windows the app helps you download Git for Windows during the welcome flow.

**Comment by billygriffin** [comment]
Hi @jennybc, I know you're busy so just a friendly ping on this. 😄 Don't hesitate to let me know if you have any other questions!

**Comment by billygriffin** [comment]
Hi @jennybc, I wanted to follow up on this. I'm also happy to amend it to just be purely factual for now and not say things like it's "great for beginners" in the explanation. It'd also be great to get this in to remove the portions about how Desktop installs Git itself, as that's no longer the case. Let me know if you'd like me to do anything additional to ease the burden on you. Thank you!

**Comment by jennybc** [comment]
Thanks for you patience. I reworded a bit, to give it a Happy Git voice, but hopefully you're still good with this.

**Comment by billygriffin** [comment]
Absolutely! It’s your guide so certainly didn’t want it to feel like our marketing material. Thank you @jennybc!

**Pull request merged**
