### PR TITLE
Replace broken link

### PR DESCRIPTION
**Pull request by jtr13**
The link to instructions on updating a fork on GitHub led to a  site in Chinese. I removed the link and added instructions. It may be worth adding that updating with this method puts you a commit ahead of the upstream repo, and in general, doesn't seem like the best way of going about things (4 clicks to create the pull request and 2 to merge???, plus switching the base is confusing.)

### CODE REVIEW

**Comment by jennybc** [comment]
Yeah I think this is a bad way to update a fork. It basically works once. It's a real shame GitHub offers no way to keep master of a fork up-to-date via the browser or automatically.

**Comment by jennybc** [comment]
But spelling it out is better than a broken link. Do you want to make a few more changes here with the context  and caveats I give above?

**Comment by jtr13** [comment]
Sure, will be glad to do that.  Just not sure about the "works once" bit. According to my testing, albeit limited, it worked more than once, it just added an extra commit each time that wouldn't be there if the fork were updated directly from upstream. However, as far as I can tell, the commit history was preserved. I'll test this again before making changes.

**Comment by jennybc** [comment]
Yeah, I mean that it leaves you with a history that is not the same as the original. You're correct that you cannot state "it does not work". But in practice, it often does not work ... for long.

**Comment by jennybc** [comment]
Thanks @jtr13 for letting me mess with the pull request! We're refining a set of functions in usethis to facilitate pull requests, for people making and reviewing them. This was a great chance for me to practice pushing back into someone else's PR.

And, after all that, I will have to close this without merging 😔

In my most recent work on Happy Git, I've come to the conclusion that there's not a GitHub/browser-based workflow that I can actually recommend for this.

https://happygitwithr.com/fork-and-clone.html#no-you-cant-do-this-via-github

So I'm going to remove all mention from the book.

Thanks again!

**Comment by jtr13** [comment]
Happy to be of service doing nothing anytime... just let me know if you need someone to open a PR. Yes, the better I understand this, the less sensible it seems to update a fork on GitHub, so best not to suggest it at all.

**Pull request closed without merging**
