### PR TITLE
Updated instructions

### PR DESCRIPTION
**Pull request by debbieyuster**
Changed instructions to reflect new wording in GitHub and RStudio

### CODE REVIEW

**Comment by jennybc** [comment]
I'm on a very current RStudio Preview version and I see prompts / menu items that are extremely close to what we already have. Not sure what version of RStudio you are on.

**Comment by debbieyuster** [comment]
Here's what I see in GitHub and RStudio Cloud (which looks different from Workbench and Desktop, I guess that's the issue):
image
image

**Comment by jennybc** [comment]
Yes, re: GitHub this update has been made (that the button says "Code").

Re: the RStudio experience, yeah, I regard desktop or workbench as a much more likely place for someone to be doing their main work and Git/GitHub setup than Cloud. How do you create the screenshot above re: a new Project on Cloud?

**Comment by debbieyuster** [comment]
Ok, thanks. For the screenshot, I just used Windows' built-in Snipping Tool to take a screengrab of RStudio Cloud, and the Snipping Tool's pen feature to circle.

**Comment by jennybc** [comment]
I was actually asking about ... what do you click on in RStudio Cloud to get this "New Project" menu?

But now that I sign in to Cloud again, I see "New Project" on the same page where Projects are listed (the "Your Workspace" view). Last night I was looking for this when I had already opened a project and there doesn't seem any obvious way to get a new Project from there. In any case, it's good to understand the Cloud experience better.

**Comment by debbieyuster** [comment]
LOL ok I'm with you now! Yes, the "New Project" button appears on what I would call the RSC homepage, with the list of projects in whatever workspace you're in.

I use RSC for teaching so that's the RStudio product I'm immersed in. There are times when this causes hiccups that are relevant to your (extremely helpful!) book. See [this discussion](https://community.rstudio.com/t/cant-open-new-project-from-git-repository-using-ssh/114960), for example. GH authentication can no longer be done by passwords, yet the "New Project from Git Repository" workflow in RSC won't work with SSH key authentication, since the keys don't persist across projects in RSC. So the only option is HTTPS + PATs. This would be a fantasticly helpful remark to include in Happy Git - I couldn't find it documented anywhere on the internet (till the above-referenced discussion) so was convinced I must be doing something wrong with SSH.

**Pull request closed without merging**
